### ISSUE TITLE
Password button enabled on field change

### ISSUE THREAD

**Issue by veljkovic92** [veljkovic92/freedom-garage#16]
Password gets lost from input, but stayes in local state on account-edit field change, so than the password submit button stays enabled.

**Comment by CodeShark20xx** [comment]
Thank you for creating an opportunity for us Open-Sourcers by posting this bug! I think I see what is causing this bug. Would you like the desired outcome to be the input field showing the password stored in local state? Or would you like the submit button to be disabled on account-edit field change?

**Comment by veljkovic92** [comment]
@CodeShark20xx Thanks for checking my code out. :) I am not 100% sure which way is more user friendly but I guess keeping the password state would be more desirable. What do you think?

**Comment by CodeShark20xx** [comment]
You're welcome! I agree. If the user accidentally switches tabs, they won't have to retype their password

**Comment by veljkovic92** [comment]
@CodeShark20xx Has sense... So, what is the problem causing the current behavior?

**Comment by CodeShark20xx** [comment]
The input element needs a value attribute that is assigned the value of {password}.

**Comment by veljkovic92** [comment]
@CodeShark20xx Yes! That's right... I totally forgot about it. Thank you a lot. :)

**Comment by veljkovic92** [comment]
> The input element needs a value attribute that is assigned the value of {password}.

@CodeShark20xx

**Comment by CodeShark20xx** [comment]
@veljkovic92 You're welcome!
